# This file was generated, do not modify it. # hide
# hideall
using Markdown
using Pkg

function print_dep_version(depname)
    deps = Pkg.dependencies()
    version = first(d for d in deps if d.second.name == depname).second.version

    "$depname: v$version"
end

println(
"""
!!! note
    These docs were autogenerated using:
      - $(print_dep_version("Makie"))
      - $(print_dep_version("GLMakie"))
      - $(print_dep_version("CairoMakie"))
      - $(print_dep_version("WGLMakie"))

    If you encounter errors with the code examples, check first that your installed versions are appropriate.
"""
)